### ISSUE TITLE
运行报错。

### ISSUE THREAD

**Issue by wl1320310292** [vipzgy/AttentionTargetClassifier#2]
不好意思，运行您的代码出现了以下问题。
Traceback (most recent call last):
  File "train.py", line 78, in <module>
    train(model, train_data, dev_data, test_data, feature_voc, label_voc, config)
  File "/home/wl/AttentionTargetClassifier-master/driver/Train.py", line 48, in train
    .format(global_step, iter, batch_iter, accuracy, correct, len(batch), during_time, loss_value[0]))
IndexError: too many indices for array

**Comment by km1994** [comment]
将 driver/Train.py 中的第47行 
print("Step:{}, Iter:{}, batch:{}, accuracy:{:.4f}({}/{}), time:{:.2f}, loss:{:.6f}"
                  .format(global_step, iter, batch_iter, accuracy, correct, len(batch), during_time, loss_value[0]))

改成 
print("Step:{}, Iter:{}, batch:{}, accuracy:{:.4f}({}/{}), time:{:.2f}, loss:{:.6f}"
                  .format(global_step, iter, batch_iter, accuracy, correct, len(batch), during_time, loss_value))

即可

**Comment by wl1320310292** [comment]
哦，谢谢
